In [ ]:
import numpy as np

In [ ]:
gamma = 0.75
alpha = 0.9

In [ ]:
location_to_state = {
    'A':0,
    'B': 1,
    'C': 2,
    'D': 3,
    'E': 4,
    'F': 5,
    'G': 6,
    'H': 7,
    'I': 8,
    'J': 9,
    'K': 10,
    'L': 11
}

In [ ]:
actions = [0,1,2,3,4,5,6,7,8,9,10,11]

In [ ]:
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,1,0,0,1,0,0,0,0,0,0],
[0,1,0,0,0,0,1,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,0,0,0],
[0,0,0,0,0,0,0,0,1,0,0,0],
[0,1,0,0,0,0,0,0,0,1,0,0],
[0,0,1,0,0,0,1000,1,0,0,0,0],
[0,0,0,1,0,0,1,0,0,0,0,1],
[0,0,0,0,1,0,0,0,0,1,0,0],
[0,0,0,0,0,1,0,0,1,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,1],
[0,0,0,0,0,0,0,1,0,0,1,0]])


In [ ]:
Q = np.array(np.zeros([12,12]))

In [ ]:
for i in range(1000):
  current_state = np.random.randint(0,12)
  playable_actions=[]
  for j in range(12):
    if R[current_state, j] > 0:
      playable_actions.append(j)

  next_state = np.random.choice(playable_actions)
  TD = R[current_state, next_state] + gamma*Q[next_state, np.argmax(Q[next_state,])] - Q[current_state,next_state]

  Q[current_state, next_state] = Q[current_state, next_state] + alpha*TD

In [ ]:
print("Q-Values:")
print(Q.astype(int))

Q-Values:
[[   0 1688    0    0    0    0    0    0    0    0    0    0]
 [1267    0 2249    0    0 1266    0    0    0    0    0    0]
 [   0 1688    0    0    0    0 2997    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2249    0    0    0    0]
 [   0    0    0    0    0    0    0    0  714    0    0    0]
 [   0 1688    0    0    0    0    0    0    0  951    0    0]
 [   0    0 2249    0    0    0 3998 2248    0    0    0    0]
 [   0    0    0 1688    0    0 2997    0    0    0    0 1687]
 [   0    0    0    0  536    0    0    0    0  950    0    0]
 [   0    0    0    0    0 1267    0    0  714    0 1267    0]
 [   0    0    0    0    0    0    0    0    0  950    0 1688]
 [   0    0    0    0    0    0    0 2249    0    0 1267    0]]


In [ ]:
state_to_location = {state: location for location, state in location_to_state.items()}


In [ ]:
def route(starting_location, ending_location):
  route=[starting_location]
  next_location = starting_location
  while (next_location != ending_location):
    starting_state = location_to_state[starting_location]
    next_state = np.argmax(Q[starting_state,])
    next_location = state_to_location[next_state]
    route.append(next_location)
    starting_location = next_location
  return route


In [ ]:
print('Route:')
route('E', 'G')

Route:


['E', 'I', 'J', 'F', 'B', 'C', 'G']